name: macaron
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with: 
          hugo-version: 'latest'
        extended: true
      - name: Build
        run: hugo --minifly
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'ref/head/master'
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./public